## Numpy
--> numerical python
* numpy is a library used to work with array
    - collection homogenious data
    - []
* numpy have functions to process array objects
* process with single and multi dimensional arrays
* array object is called as ndarray

In [ ]:
[] --> will indicate list python

In [1]:
l = [1,2,3,4,5,6]
print(type(l))

<class 'list'>


In [2]:
import numpy as np
l = [1,2,3,4,5,6]
arr = np.array(l)
arr

array([1, 2, 3, 4, 5, 6])

In [6]:
arr2 = np.array([[12,3,4,5],[4,5,6,7]])
arr2

array([[12,  3,  4,  5],
       [ 4,  5,  6,  7]])

In [3]:
l = [1,2,3]
l1 = [4,5,6]
arr1 = np.array(l,l1)
arr1

TypeError: data type not understood

In [4]:
l = [1,2,3]
l1 = [4,5,6]
arr1 = np.array([l,l1])
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
arr1.shape

(2, 3)

In [8]:
arr1.size

6

In [9]:
arr1.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [10]:
#l = [1,2,3,4]
l = input().split()
l

12 3 4 56


['12', '3', '4', '56']

In [11]:
l = list(map(int,l))
l

[12, 3, 4, 56]

In [12]:
l1 = list(map(int,input().split()))
l1

1 2 3 4


[1, 2, 3, 4]

In [13]:
darr = np.array([l,l1])
darr

array([[12,  3,  4, 56],
       [ 1,  2,  3,  4]])

In [15]:
r = np.arange(1,50)
r

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [16]:
r.reshape(7,7)

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28],
       [29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42],
       [43, 44, 45, 46, 47, 48, 49]])

In [17]:
r.reshape(7,9)

ValueError: cannot reshape array of size 49 into shape (7,9)

In [18]:
ran = np.random.randint(1,50,size=(5,5))
ran

array([[29, 14, 43, 45, 16],
       [19, 31,  1,  3, 15],
       [ 9,  6,  8,  4, 28],
       [26, 49,  3,  2, 48],
       [31, 17, 38,  7, 35]])

In [19]:
ran = np.random.randint(1,50,size=(5,6))
ran

array([[15, 28, 36, 20, 49, 21],
       [ 6, 32, 14, 12, 43, 43],
       [43, 25, 46, 42, 21,  5],
       [15, 22,  4, 23, 24,  4],
       [ 3, 21, 13, 12,  5, 24]])

In [21]:
ran = np.random.randint(1,100,size=(5,10))
ran

array([[80, 57, 82, 27,  4, 39, 52, 10, 27, 48],
       [ 3, 42, 61, 25, 36, 74, 35, 91, 17, 12],
       [78, 83,  2, 24, 66, 92, 99, 53, 97, 81],
       [51, 70, 50, 74, 85, 85, 68, 21, 85, 45],
       [70, 13, 50, 12, 71, 51, 27, 40, 80, 96]])

In [22]:
ran1 = ran

In [23]:
ran1.shape

(5, 10)

In [24]:
ran1.reshape(10,5)

array([[80, 57, 82, 27,  4],
       [39, 52, 10, 27, 48],
       [ 3, 42, 61, 25, 36],
       [74, 35, 91, 17, 12],
       [78, 83,  2, 24, 66],
       [92, 99, 53, 97, 81],
       [51, 70, 50, 74, 85],
       [85, 68, 21, 85, 45],
       [70, 13, 50, 12, 71],
       [51, 27, 40, 80, 96]])

In [25]:
ran1.size

50

In [26]:
ran1.max()

99

In [27]:
ran1.min()

2

In [29]:
ran1.mean()

52.82

In [31]:
ran1.std()

28.391329662416304

In [ ]:
1 1
1 2
null
unit
daignol
inverse

#### numpy inbuil functions
1. zeros
2. ones
3. vstack
4. hstack

In [32]:
nul = np.zeros((3,4))
nul

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [35]:
nul = np.zeros((3,4),int)
nul

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [36]:
unit = np.ones((3,3))
unit

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [37]:
unit = np.ones((3,3),int)
unit

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [38]:
vs = np.vstack([unit,unit+5])
vs

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]])

In [39]:
hs = np.hstack([unit,unit+5])
hs

array([[1, 1, 1, 6, 6, 6],
       [1, 1, 1, 6, 6, 6],
       [1, 1, 1, 6, 6, 6]])

In [40]:
ran1

array([[80, 57, 82, 27,  4, 39, 52, 10, 27, 48],
       [ 3, 42, 61, 25, 36, 74, 35, 91, 17, 12],
       [78, 83,  2, 24, 66, 92, 99, 53, 97, 81],
       [51, 70, 50, 74, 85, 85, 68, 21, 85, 45],
       [70, 13, 50, 12, 71, 51, 27, 40, 80, 96]])

In [41]:
vs = np.vstack([ran1,ran1-10])
vs

array([[80, 57, 82, 27,  4, 39, 52, 10, 27, 48],
       [ 3, 42, 61, 25, 36, 74, 35, 91, 17, 12],
       [78, 83,  2, 24, 66, 92, 99, 53, 97, 81],
       [51, 70, 50, 74, 85, 85, 68, 21, 85, 45],
       [70, 13, 50, 12, 71, 51, 27, 40, 80, 96],
       [70, 47, 72, 17, -6, 29, 42,  0, 17, 38],
       [-7, 32, 51, 15, 26, 64, 25, 81,  7,  2],
       [68, 73, -8, 14, 56, 82, 89, 43, 87, 71],
       [41, 60, 40, 64, 75, 75, 58, 11, 75, 35],
       [60,  3, 40,  2, 61, 41, 17, 30, 70, 86]])

In [47]:
dai = np.zeros((5,5),int)
np.diag([1,1,1,1,1])

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [50]:
np.diag([1,1,1])

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [4]:
m = np.array([[1,2],[3,4]])
from numpy.linalg import inv
res = inv(m)
res

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [7]:
mat2 = np.random.randint(1,25,size=(4,4))
res2 = inv(mat2)
res2

array([[-0.49924281,  0.13377082, -0.46744069,  0.48107017],
       [ 0.22195861, -0.02064614,  0.24422009, -0.24896517],
       [-0.10822817,  0.01302373, -0.05381121,  0.10570419],
       [ 0.44336194, -0.10605755,  0.36456335, -0.38404846]])

In [8]:
mat2 + mat2

array([[36,  2,  8, 46],
       [48, 42,  4, 34],
       [ 6, 14, 42, 10],
       [34,  4, 48, 48]])

In [9]:
mat2 - mat2

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [10]:
mat2 * mat2

array([[324,   1,  16, 529],
       [576, 441,   4, 289],
       [  9,  49, 441,  25],
       [289,   4, 576, 576]])

In [11]:
mat2 / mat2

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])